title: Diego Villacís
description: Mi Blog Personal
author: Diego Villacís
logo: /static/img/avatar.png
github: https://github.com/diegovillacis10
about: Frustated Soccer Player / Software Dev

baseurl: ""
url: "http://diegovillacis.xyz"

disqus_shortname: diegovillacis
google_analytics: UA-00000000-1

share:
  twitter_username: diegovillacis10
  fb_appid: 1168847956489794


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
